### ISSUE TITLE
Link to university page down...

### ISSUE THREAD

**Issue by martin-raden** [DH-Center-Tuebingen/Spacialist#393]
Hi,
the link to the university page of the project (start page) is outdated..

https://escience.uni-tuebingen.de/spacialist

:)

Best,
Martin

**Comment by DavidKi** [comment]
Hi, 
I have updated the link to point to [https://uni-tuebingen.de/de/211099](https://uni-tuebingen.de/de/211099).

@v1r0x Do we have a better URL for the project like dh-center.uni-tuebingen.de/spacialist (which right now leads only to the apache default site)

**Comment by v1r0x** [comment]
Where did you find these links?

**Comment by martin-raden** [comment]
think its project settings or something... the link that shows up in the upper right corner of the projects main page...

**Comment by v1r0x** [comment]
I've updated the link in the [`About` section](https://github.com/DH-Center-Tuebingen/Spacialist). Is this what you mean?
@DavidKi which link is updated?

**Comment by martin-raden** [comment]
tiptop ...
