### ISSUE TITLE
Error message "Server down" 

### ISSUE THREAD

**Issue by ReKlug** [DH-Center-Tuebingen/Spacialist#406]
When trying to work with the fotos, there comes the Error:
POST Request [api/v1/file/unlinked](https://escience-center.uni-tuebingen.de/spacialist/thorikos/s/api/v1/file/unlinked) failed with status 500.
Error Message: { "message": "Server Error) 
Steps to reproduce
1.  open the database
2. open "Dateien"
3.  choose unverknüpfte Dateien or alle Dateien
4. choose a file
5. 
Expected behaviour
Ther should come a list of the pictures with this filter

Actual behaviour
Instead, neither the picuters are visible with all pictures, nor with the filter. Only the Error message

Spacialist version:** v0.7.3-giza

(https://user-images.githubusercontent.com/79839740/199985626-91c96786-3aef-4c88-8c50-fc525a704ee6.JPG)

**Comment by v1r0x** [comment]
Fixed
