### ISSUE TITLE
saving not possible in Camarina Database

### ISSUE THREAD

**Issue by ReKlug** [DH-Center-Tuebingen/Spacialist#416]
It is not possible to save changes in several entities., but not in all entites.

Description
When I try to change or fill in new data in the entity SF1 -Fiume Grande SP 1, saving is not possible. If I try the same in the next entity SF 1- Fiume Grande SP2, there is no problem at all.

Steps to reproduce (maybe you can only reproduce it in our database...)
1. Open the entity SF1 - Fiume Grande SP 1 (under the top entity Fiume Grande)
2. Fill in a new concept into the table "Prospektionsfunde"
3.create a new empty line (otherwise it never saves changes)
4.try to save the changes

Expected behaviour
I expect that the changes are saved

Actual behaviour
it does not save the changes

Screenshots

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Laravel Version:**

**Spacialist version:**

**List of activated modules:**
<details>
<summary>Module List</summary>
</details>

**Are you using external storage, if yes which one:** local/ftp/aws/...

### Client configuration
**Browser:**

**Operating system:**

#### Webserver error log
<details>
<summary>Webserver error log</summary>
```
Insert your webserver log here
```
</details>

#### Laravel log (storage/logs/laravel.log)
<details>
<summary>Laravel log</summary>
```
Insert your Laravel log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log (e.g. Right click > Inspect Element > (Choose "Console" in new opened side bar))
b) The network log
c) ...
```
</details>

![FiumeGrande](https://user-images.githubusercontent.com/79839740/216398176-9549f215-291d-4aa0-8abd-db7759c15389.JPG)
![Spacialist](https://user-images.githubusercontent.com/79839740/216398764-21c3dbef-9cdf-4fd6-af2a-937cf817f177.JPG)

**Comment by v1r0x** [comment]
The data of that entity was corrupted in the database. I don't know how that happened, because it was not even close to how the data should look.
Should work again now.

**Comment by ReKlug** [comment]
Danke Vinzenz.

Von: Vinzenz Rosenkranz ***@***.***>
Gesendet: Montag, 6. Februar 2023 11:17
An: DH-Center-Tuebingen/Spacialist ***@***.***>
Cc: Klug, Rebecca Diana ***@***.***>; Author ***@***.***>
Betreff: Re: [DH-Center-Tuebingen/Spacialist] saving not possible in Camarina Database (Issue #416)


The data of that entity was corrupted in the database. I don't know how that happened, because it was not even close to how the data should look.
Should work again now.

**Comment by ReKlug** [comment]
Lieber Vinzenz,

heute wurden wieder Daten in Spacialist eingegeben. Leider ist es jetzt noch schlimmer. Es können in keiner Surveyfläche Daten gespeichert werden, obwohl angezeigt wird, dass gespeichert wurde. Geht man dann auf einen anderen Datensatz und dann wieder zurück, sind alle vorherigen Änderungen wieder weg. Anfangs ging es heute, dann nicht mehr.

Unser Verdacht: es hat etwas mit Änderungen im Thesaurus zu tun. Ich habe einen schon vorhandenen Begriff mit einer weiteren Kategorie verknüpft (Unguentarium war als Gefäßform und ich habe das Attribut zusätzlich mit Grobkeramik verknüpft). Nachdem die Studentin dann den Begriff einmal benutzt hat, ging nichts mehr.

Schöne Grüße
Rebecca

Von: Vinzenz Rosenkranz ***@***.***>
Gesendet: Montag, 6. Februar 2023 11:17
An: DH-Center-Tuebingen/Spacialist ***@***.***>
Cc: Klug, Rebecca Diana ***@***.***>; Author ***@***.***>
Betreff: Re: [DH-Center-Tuebingen/Spacialist] saving not possible in Camarina Database (Issue #416)


The data of that entity was corrupted in the database. I don't know how that happened, because it was not even close to how the data should look.
Should work again now.
