### ISSUE TITLE
website certificate is invalid

### ISSUE THREAD

**Issue by ReKlug** [DH-Center-Tuebingen/Spacialist#423]
The Website certificate is invalid (Agrigent, Camarina, Thorikos). In Firefox I can't even add an exception anymore and there are also problems in edge and chrome (118.0.2 (64-Bit)).
The Information is, that the certifcate is valid only for dh-center.uni-tuebingen.de, rdmo.dh-center.uni-tuebingen.de but not for escience-center.uni-tuebingen.de.

</details>
<img width="703" alt="Screenshot 2023-10-25 213736" src="https://github.com/DH-Center-Tuebingen/Spacialist/assets/79839740/45826937-341d-4191-a18c-d98eef90981f">

**Comment by v1r0x** [comment]
You should switch from `escience-center` to `dh-center` in your URL
