### ISSUE TITLE
Attribute Search is not showing proper results

### ISSUE THREAD

**Issue by Severino** [DH-Center-Tuebingen/Spacialist#433]
## What is going wrong?
When searching in the Attr. List in the Data Model Builder the search function is bro

### Steps to reproduce
1. Goto DME
2. Create new Attr.
3. Search for existing  component e.g. 'Textbox'
4. 'No results here'

## What should happen?
Show the matching components

## Possible cause
The field does search, but matches not the label but the underlying 'id'.
E.g. searching for 'stringf' has the result 'Textbox'

**Comment by v1r0x** [comment]
fixed in latest `release-0.10`
