### ISSUE TITLE
Not allowed to see data/photos

### ISSUE THREAD

**Issue by ReKlug** [DH-Center-Tuebingen/Spacialist#517]
In the Agrigent database I am not allowed to see the data, means pictures. I am the administrator and should not have any restrictions. When choosing a find and wanting to see the fotos, I am getting the response "Fehlermeldung: du hast keine Berechtigung Dateien anzusehen".
What I would expect: to see the fotos.

The database is hosted in Tübingen.

I included two screenshots.

In the Camarina Database, as well hosted in Tübingen, I did not get a bug report, but I am not able to see the fotos.
<img width="307" alt="agrigent_fehler_12_10_24" src="https://github.com/user-attachments/assets/27f2e540-0f42-4703-bffb-72e7d18dbee8">
<img width="354" alt="Camarina_Fehler_12_10_24" src="https://github.com/user-attachments/assets/26321611-231a-462f-a298-16f5c0cdcec4">

**Comment by v1r0x** [comment]
Your issues should be fixed in both databases.
