### ISSUE TITLE
picture upload is not working

### ISSUE THREAD

**Issue by Julius-Roch** [DH-Center-Tuebingen/Spacialist#521]
Thorikos-Data base: it is not possible to upload pictures: POST-Anfrage an den Endpunkt file/new ist mit Statuscode 500 fehlgeschlagen.
![Bild_2024-10-23_093453873](https://github.com/user-attachments/assets/a6aa2290-90f8-4168-a187-86f12f0c99b1)

**Comment by Julius-Roch** [comment]
Same issue with the camarina and agrigent data bases.

**Comment by v1r0x** [comment]
Thanks for the report!

It should work again. Can you please confirm @Julius-Roch ?

**Comment by Julius-Roch** [comment]
Unfortunately, the error message still occurs @v1r0x
