### ISSUE TITLE
Linked files are not loaded

### ISSUE THREAD

**Issue by Julius-Roch** [DH-Center-Tuebingen/Spacialist#538]
Thorikos-Data base: if there are more than 15 linked files, only the first 15 are displayed and the others are not loaded when scrolling down. Furthermore, the display changes from “15 of 45 files displayed” to “No files displayed”, for example.

![Thorikos_1](https://github.com/user-attachments/assets/61b89ce1-9ef0-4ac8-86dc-9c92017fd096)
![Thorikos_2](https://github.com/user-attachments/assets/235cf408-9008-475b-8e34-9941055faaeb)

**Comment by v1r0x** [comment]
Thanks for the report!
It is fixed now and should load all images correctly.

**Comment by Julius-Roch** [comment]
Thank you!
